server:  port: 9999
  servlet:  
    context-path: "/activiti-app"
spring:  activiti:    check-process-definitions: false  
  jpa: 
    properties: 
      hibernate: 
        cache:
          use_second_level_cache: false      open-in-view: true       generate-ddl: true         aop:    proxy-target-class: false          
  liquibase:
    enabled: false
 